[package]
name = "accessible_gis"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "fs-all", "dialog-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ndarray = "0.15.6"
geo = {"version" = "0.28.0", "features" = ["serde", "use-proj"] }
proj = "0.27.2"
geo-types = {"version" = "0.7.13", "features" = ["serde", "use-rstar_0_12"] }
itertools = "0.12.1"
geos = { "version" = "8.3.1", "features" = ["geo" ,"wkt"] }
gdal = {"version" = "0.16.0", "features" = ["bindgen", "ndarray"] }
csv = "1.3.0"
num-traits = "0.2.18"
statrs = "0.16.0"
rstar = {"version" = "0.12.0", "features" = [ "serde", "mint"] }
mint = "0.5.9"
specta = "1.0.5"
tauri-specta = { version = "1.0.2", features = ["javascript", "typescript"] }
enum-as-inner = "0.6.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
